#FROM ubuntu:22.10
#RUN apt-get update && \ 
#	apt-get install -y cowsay && \
#	ln -s /usr/games/cowsay /usr/bin/cowsay && \
#	rm -rf /var/lib/apt/lists/*
#COPY test.txt /
#CMD ["cowsay"]


FROM ubuntu:22.10
COPY test.txt / 
CMD sleep 600
